services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    container_name: zero-trust-gateway
    ports:
      - "443:443"
    networks:
      - public_net
      - internal_net
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./certs:/etc/envoy/certs:ro

  auth-service:
    build: ../auth_service
    container_name: auth-service
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    expose:
      - "8080"
    networks:
      - internal_net

  resource-api:
    build: ../resource-api
    container_name: zero-trust-resource-api
    expose:
      - "8080"
    networks:
      - internal_net

networks:
  public_net:
  internal_net:
    internal: true
