services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    container_name: zero-trust-gateway
    ports:
      - "443:443" # Cổng DUY NHẤT lộ diện ra thế giới bên ngoài
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./certs:/etc/envoy/certs:ro
    networks:
      - public_net
      - internal_net
    depends_on:
      - auth-service
      - resource-api

  auth-service:
    image: mendhak/http-https-echo:latest
    container_name: mock-auth-service
    
    expose:
      - "8080" # Chỉ mở cổng âm bên trong mạng nội bộ Docker cho Envoy gọi
    networks:
      - internal_net

  resource-api:
    image: mendhak/http-https-echo:latest
    container_name: mock-resource-api

    expose:
      - "8080" # Chỉ mở cổng âm bên trong mạng nội bộ Docker cho Envoy gọi
    networks:
      - internal_net

networks:
  public_net:
    name: zero-trust-public-network
  internal_net:
    name: zero-trust-internal-network
    internal: true # Ép mạng này biệt lập hoàn toàn, không có đường ra Internet
